modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="tconstruct_compatible"
version="1.0.0"
displayName="TConstruct Compatible"
credits="null"
displayURL="https://mcreator.net"
authors="HLFT"

[[dependencies.tconstruct_compatible]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




